<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/Data_Frame_Indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = {'Yili': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
        'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
        "Temp": [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
        'Zichlik': [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}
df = pd.DataFrame(data)

In [4]:
df

   Yili  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [5]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [6]:
## Reindex
ind = [21, 20, 19, 18, 17, 16, 15, 10]
ind.sort()

In [7]:
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [8]:
df.reindex(ind)

    Yili  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [9]:
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [10]:
df.reindex([10, 15, 20])

    Yili  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
20  2020        33.5  1.48    78.68

In [15]:
df.reindex(index=range(10, 22), method='nearest')

    Yili  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [16]:
df.reindex(index=range(10, 22), method='ffill')

    Yili  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2015        30.9  1.64    72.71
12  2015        30.9  1.64    72.71
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [19]:
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [20]:
df.reindex(columns=['Aholi soni', 'Temp', 'Zichlik'])

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13
16        31.4  1.66    73.91
15        30.9  1.64    72.71
10        28.5  1.53    67.03

In [21]:
df.head()

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13

In [22]:
df.sample()

    Yili  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03

In [25]:
df.sample(2)

    Yili  Aholi soni  Temp  Zichlik
19  2019        32.9  1.56    77.53
16  2016        31.4  1.66    73.91

In [29]:
df.loc[[10,15, 18,20], ['Aholi soni', 'Temp', 'Zichlik']]

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
18        32.5  1.62    76.34
20        33.5  1.48    78.68

In [30]:
df2 = df.drop(10)

In [31]:
df2

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71

In [32]:
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [38]:
df.drop('Yili', axis='columns')

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13
16        31.4  1.66    73.91
15        30.9  1.64    72.71
10        28.5  1.53    67.03

In [39]:
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [40]:
df.drop('Yili', axis=1)

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13
16        31.4  1.66    73.91
15        30.9  1.64    72.71
10        28.5  1.53    67.03

In [41]:
df

    Yili  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [42]:
df_new = df.drop('Yili', axis='columns')

In [43]:
df_new

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13
16        31.4  1.66    73.91
15        30.9  1.64    72.71
10        28.5  1.53    67.03

In [44]:
df.drop([17, 18], inplace=True)