<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/pandas_arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Foydali funksiyalar

####Arifmetik amallar

In [2]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [4]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [7]:
df1 = pd.DataFrame(np.arange(9.).reshape(3, 3), columns=list('bcd'), index=['Olma', 'Anor', 'Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4, 3), columns=list('abc'), index=["Olma", 'Anor', 'Qovun', 'Anjir'])

In [8]:
df1

        b    c    d
Olma  0.0  1.0  2.0
Anor  3.0  4.0  5.0
Uzum  6.0  7.0  8.0

In [9]:
df2

         a     b     c
Olma   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Qovun  6.0   7.0   8.0
Anjir  9.0  10.0  11.0

In [10]:
df1+df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [11]:
df1.add(df2)

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [12]:
df1.add(df2, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [13]:
df2.sub(df1, fill_value=0)

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [14]:
df2-df1

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  1.0  1.0 NaN
Olma  NaN  1.0  1.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [15]:
df1.sub(df2, fill_value=0)

         a     b     c    d
Anjir -9.0 -10.0 -11.0  NaN
Anor  -3.0  -1.0  -1.0  5.0
Olma   0.0  -1.0  -1.0  2.0
Qovun -6.0  -7.0  -8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [16]:
df2.rsub(df1, fill_value=0)

         a     b     c    d
Anjir -9.0 -10.0 -11.0  NaN
Anor  -3.0  -1.0  -1.0  5.0
Olma   0.0  -1.0  -1.0  2.0
Qovun -6.0  -7.0  -8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [17]:
df2.div(df1)

        a         b     c   d
Anjir NaN       NaN   NaN NaN
Anor  NaN  1.333333  1.25 NaN
Olma  NaN       inf  2.00 NaN
Qovun NaN       NaN   NaN NaN
Uzum  NaN       NaN   NaN NaN

In [18]:
df2.rdiv(df1)

        a     b    c   d
Anjir NaN   NaN  NaN NaN
Anor  NaN  0.75  0.8 NaN
Olma  NaN  0.00  0.5 NaN
Qovun NaN   NaN  NaN NaN
Uzum  NaN   NaN  NaN NaN

In [19]:
df = pd.DataFrame(np.arange(1, 13.).reshape(3, 4), index=list('abc'), columns=['Olma', 'Anor', 'Qovun', 'Anjir'])
obj = pd.Series([1, 1, 2, 2], index=df.columns)

In [20]:
obj

Olma     1
Anor     1
Qovun    2
Anjir    2
dtype: int64

In [21]:
df

   Olma  Anor  Qovun  Anjir
a   1.0   2.0    3.0    4.0
b   5.0   6.0    7.0    8.0
c   9.0  10.0   11.0   12.0

In [22]:
obj+df

   Olma  Anor  Qovun  Anjir
a   2.0   3.0    5.0    6.0
b   6.0   7.0    9.0   10.0
c  10.0  11.0   13.0   14.0

In [23]:
obj = pd.Series([2, 3, 1], index=['Olma', 'Uzum', 'Qovun'])

In [24]:
obj

Olma     2
Uzum     3
Qovun    1
dtype: int64

In [25]:
df.sub(obj)

   Anjir  Anor  Olma  Qovun  Uzum
a    NaN   NaN  -1.0    2.0   NaN
b    NaN   NaN   3.0    6.0   NaN
c    NaN   NaN   7.0   10.0   NaN

In [26]:
df

   Olma  Anor  Qovun  Anjir
a   1.0   2.0    3.0    4.0
b   5.0   6.0    7.0    8.0
c   9.0  10.0   11.0   12.0

In [27]:
obj["Olma"]

np.int64(2)

In [28]:
df+obj['Olma']

   Olma  Anor  Qovun  Anjir
a   3.0   4.0    5.0    6.0
b   7.0   8.0    9.0   10.0
c  11.0  12.0   13.0   14.0

#### Pandas obyekti elementlariga funksiyalarni qo'llash

In [34]:
df = pd.DataFrame(np.random.randn(3, 4), index=list('abc'), columns=["Olma", 'Anor', 'Qovun', 'Anjir'])
df

       Olma      Anor     Qovun     Anjir
a -0.628590 -0.063706  1.109746  0.394364
b -0.051528  0.742456  0.116980 -1.396554
c  1.909246 -1.069473 -0.026049 -1.269625

In [35]:
np.abs(df)

       Olma      Anor     Qovun     Anjir
a  0.628590  0.063706  1.109746  0.394364
b  0.051528  0.742456  0.116980  1.396554
c  1.909246  1.069473  0.026049  1.269625

In [36]:
df

       Olma      Anor     Qovun     Anjir
a -0.628590 -0.063706  1.109746  0.394364
b -0.051528  0.742456  0.116980 -1.396554
c  1.909246 -1.069473 -0.026049 -1.269625

In [37]:
df.mean()

Olma     0.409709
Anor    -0.130241
Qovun    0.400226
Anjir   -0.757272
dtype: float64

In [38]:
df.apply(np.abs)

       Olma      Anor     Qovun     Anjir
a  0.628590  0.063706  1.109746  0.394364
b  0.051528  0.742456  0.116980  1.396554
c  1.909246  1.069473  0.026049  1.269625

In [40]:
df.apply(sum, axis=1)

a    0.811814
b   -0.588645
c   -0.455902
dtype: float64

In [41]:
f = lambda x: x.max() - x.min()

In [42]:
df.apply(f)

Olma     2.537836
Anor     1.811929
Qovun    1.135796
Anjir    1.790917
dtype: float64

In [44]:
def faa(x):
  return pd.Series([x.max(), x.min()], index=['max', 'min'])

In [45]:
df.apply(faa)

         Olma      Anor     Qovun     Anjir
max  1.909246  0.742456  1.109746  0.394364
min -0.628590 -1.069473 -0.026049 -1.396554

In [46]:
df = pd.DataFrame(np.arange(1, 13).reshape(3, 4), index=list('abc'), columns=['olma', 'anor', 'qovun', 'anjir'])
df

   olma  anor  qovun  anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [47]:
df.applymap(lambda x: x*x)

/tmp/ipykernel_10003/3316139181.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x*x)

   olma  anor  qovun  anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144

###Tartiblash (sort) va Reytinglash (ranking)

In [48]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [49]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [50]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [51]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [53]:
df.shape

(2499, 12)

In [54]:
df.sort_index()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [55]:
df.sort_index(axis=1)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [56]:
df.sort_index(axis=1, inplace=True)

In [57]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [58]:
df.sort_index(axis=1, ascending=False)

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan

In [59]:
df.sort_index(axis=1, ascending=True)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [61]:
df.sort_values(by='price')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
455,chevrolet,silver,17 hours left,usa,167650486,268040,door,0,texas,salvage insurance,1g1zt53f46f254868,2006
421,bmw,gray,2 days left,usa,167425906,216657,door,0,utah,salvage insurance,wbaam3346yfp77118,2000
420,audi,black,19 hours left,usa,167419563,181896,door,0,california,salvage insurance,waudg74f05n113751,2005
419,kia,silver,16 hours left,usa,167247592,148463,wagon,0,indiana,salvage insurance,knafg525787197602,2008
293,chevrolet,gray,17 hours left,usa,167417659,258631,pickup,0,texas,salvage insurance,1gccs1445wk226994,1998
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017

In [62]:
df.sort_values(by='price', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
318,chevrolet,black,18 hours left,usa,167418694,117059,door,0,colorado,salvage insurance,kl1td66e39b645208,2009
305,ford,gold,8 days left,usa,167610324,246065,door,0,kansas,salvage insurance,1fafp55u03a242094,2003
510,ford,silver,17 hours left,usa,167357806,86841,door,0,oklahoma,salvage insurance,3fahp0ga3ar366961,2010
522,ford,red,17 hours left,usa,167357813,145483,door,0,oklahoma,salvage insurance,1fmcu03128kc80487,2008
144,dodge,silver,2 days left,usa,167756167,123660,door,0,utah,salvage insurance,1c3cdzab0en111068,2014

In [63]:
df.sort_values(by=['price', 'mileage'])

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
309,chevrolet,maroon,18 hours left,usa,167418651,0,door,0,wyoming,salvage insurance,3gnek12t74g240524,2004
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
349,heartland,white,7 days left,usa,167266321,1,sundance,0,pennsylvania,clean vehicle,5sfgf29269e031344,2009
196,ford,white,2 days left,usa,167656523,76858,mpv,0,texas,clean vehicle,1fbax2cv0hkb32599,2017
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017

In [64]:
df.sort_values(by=['price', 'mileage'], ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
196,ford,white,2 days left,usa,167656523,76858,mpv,0,texas,clean vehicle,1fbax2cv0hkb32599,2017
349,heartland,white,7 days left,usa,167266321,1,sundance,0,pennsylvania,clean vehicle,5sfgf29269e031344,2009
309,chevrolet,maroon,18 hours left,usa,167418651,0,door,0,wyoming,salvage insurance,3gnek12t74g240524,2004
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993

In [65]:
df.sort_values(by='year', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2306,nissan,black,7 hours left,usa,167129224,264,cargo,19000,california,clean vehicle,3n6cm0kn9lk693851,2020
2305,nissan,gray,2 days left,usa,167743353,15387,rogue,14700,pennsylvania,clean vehicle,knmat2mv5lp500471,2020
2302,nissan,silver,21 hours left,usa,167725016,19597,rogue,21100,south carolina,clean vehicle,5n1at2mt6lc714032,2020
657,chevrolet,gray,21 hours left,usa,167781406,179,trax,22000,california,clean vehicle,3gncjksbxll181398,2020
1217,ford,silver,21 hours left,usa,167722215,5920,explorer,32500,missouri,clean vehicle,1fmsk8dh2lga15480,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
362,ford,white,2 days left,usa,167361489,206162,pickup,25,georgia,salvage insurance,1ftdf15y2rnb12612,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
405,ford,white,17 hours left,usa,167611661,41577,door,25,arkansas,salvage insurance,2ftcf15y9eca14589,1984
32,chevrolet,red,22 hours left,usa,167763370,46226,camaro,29800,pennsylvania,clean vehicle,1q87t3n166389,1973

###Reytinglash

In [66]:
df['rating'] = df['year'].rank()

In [67]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008,70.5
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011,115.0
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018,1362.0
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014,336.5
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018,1362.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019,2005.5
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018,1362.0
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018,1362.0
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018,1362.0
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018,1362.0

In [68]:
df.sort_values('year')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating
32,chevrolet,red,22 hours left,usa,167763370,46226,camaro,29800,pennsylvania,clean vehicle,1q87t3n166389,1973,1.0
405,ford,white,17 hours left,usa,167611661,41577,door,25,arkansas,salvage insurance,2ftcf15y9eca14589,1984,2.0
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993,3.0
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994,4.5
362,ford,white,2 days left,usa,167361489,206162,pickup,25,georgia,salvage insurance,1ftdf15y2rnb12612,1994,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,ford,gray,21 hours left,usa,167749593,2452,fusion,23400,michigan,clean vehicle,3fa6p0hd6lr110753,2020,2475.5
1642,ford,black,2 days left,usa,167570001,17858,fusion,20600,virginia,clean vehicle,3fa6p0cd8lr115427,2020,2475.5
206,chevrolet,black,3 days left,usa,167756877,7232,vehicl,25,kentucky,salvage insurance,2gnaxkev6l6128374,2020,2475.5
1640,ford,red,2 days left,usa,167569997,12748,mustang,27000,virginia,clean vehicle,1fatp8uh3l5101487,2020,2475.5
1638,ford,silver,2 days left,usa,167569992,23984,fusion,20000,virginia,clean vehicle,3fa6p0cd0lr116667,2020,2475.5

In [73]:
df['rating']=df['price'].rank(method='min')

In [74]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008,380.0
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011,156.0
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018,326.0
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014,1824.0
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019,475.0
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018,567.0
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018,567.0
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018,567.0
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018,567.0

In [75]:
df.sort_values('price')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating
455,chevrolet,silver,17 hours left,usa,167650486,268040,door,0,texas,salvage insurance,1g1zt53f46f254868,2006,1.0
421,bmw,gray,2 days left,usa,167425906,216657,door,0,utah,salvage insurance,wbaam3346yfp77118,2000,1.0
420,audi,black,19 hours left,usa,167419563,181896,door,0,california,salvage insurance,waudg74f05n113751,2005,1.0
419,kia,silver,16 hours left,usa,167247592,148463,wagon,0,indiana,salvage insurance,knafg525787197602,2008,1.0
293,chevrolet,gray,17 hours left,usa,167417659,258631,pickup,0,texas,salvage insurance,1gccs1445wk226994,1998,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019,2495.0
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019,2496.0
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019,2497.0
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019,2498.0
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017,2499.0

In [76]:
df['raiting'] = df['mileage'].rank(method='average')

In [80]:
df.sort_values('mileage')

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year,rating,raiting
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993,1.0,3.5
1236,ford,no_color,2 days left,usa,167773673,0,door,4200,pennsylvania,clean vehicle,1fadp3j23dl155179,2013,258.0,3.5
309,chevrolet,maroon,18 hours left,usa,167418651,0,door,0,wyoming,salvage insurance,3gnek12t74g240524,2004,1.0,3.5
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994,1.0,3.5
504,peterbilt,blue,17 hours left,usa,167529787,0,truck,100,florida,salvage insurance,1xp4d49x1cd144875,2012,67.0,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,chevrolet,red,21 hours left,usa,167781223,507985,pickup,2000,wisconsin,clean vehicle,1gcgc24u53z128586,2003,123.0,2495.0
490,peterbilt,gold,17 hours left,usa,167529786,902041,truck,475,florida,salvage insurance,1xp4d49x9cd123630,2012,76.0,2496.0
516,peterbilt,blue,17 hours left,usa,167529788,982486,truck,0,florida,salvage insurance,1xp7d49x09d784257,2009,1.0,2497.0
1827,ford,silver,21 hours left,usa,167727773,999999,door,3200,south carolina,clean vehicle,1fadp3k21dl266148,2013,181.0,2498.0
528,peterbilt,color:,17 hours left,usa,167529842,1017936,truck,1025,georgia,salvage insurance,1xp7d49x0ad793710,2010,94.0,2499.0