<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Pandas kutubxonasi bu - aynan data science ga yo'naltirilib u ma'lumotlarga ishlov berish uchun ishlatiladi

In [3]:
import pandas as pd

In [4]:
import numpy as np

##pandas ma'luomotlar tuzilmasida ikkita muhim malumot tuzilmasi bor ular : Series va dataframe

Series

In [5]:
from pandas import Series

In [10]:
obj = Series([4, 2, 6, 8, 6, 7.8])

In [11]:
type(obj)

pandas.core.series.Series

In [12]:
obj

0    4.0
1    2.0
2    6.0
3    8.0
4    6.0
5    7.8
dtype: float64

In [13]:
print(obj)

0    4.0
1    2.0
2    6.0
3    8.0
4    6.0
5    7.8
dtype: float64

In [14]:
obj.values

array([4. , 2. , 6. , 8. , 6. , 7.8])

In [15]:
obj.index

RangeIndex(start=0, stop=6, step=1)

In [16]:
obj[2]

np.float64(6.0)

In [17]:
obj2 = Series([2, 5, 6, 8, 9, 7, 3, 7], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [18]:
obj2['b']

np.int64(5)

In [19]:
obj2[['a', 'd', 'h', 'f']]

a    2
d    8
h    7
f    7
dtype: int64

In [20]:
obj2[['b', 'b', 'b', 'b']]

b    5
b    5
b    5
b    5
dtype: int64

In [21]:
obj2[obj2>4]

b    5
c    6
d    8
e    9
f    7
h    7
dtype: int64

In [22]:
obj2 * 2

a     4
b    10
c    12
d    16
e    18
f    14
g     6
h    14
dtype: int64

In [23]:
obj2

a    2
b    5
c    6
d    8
e    9
f    7
g    3
h    7
dtype: int64

In [24]:
np.exp(obj2)

a       7.389056
b     148.413159
c     403.428793
d    2980.957987
e    8103.083928
f    1096.633158
g      20.085537
h    1096.633158
dtype: float64

In [25]:
obj2['a']

np.int64(2)

In [26]:
obj2

a    2
b    5
c    6
d    8
e    9
f    7
g    3
h    7
dtype: int64

#pythonda yozilgan lug'atlarni osongina series malumotlar turiga o'tkazish mumkin

In [27]:
cars_dict = {'Malibu': 40000, 'Lacetti': 20000, 'Toyota': 45000, 'Mazda':52000, 'Honda': 38000}

In [28]:
type(cars_dict)

dict

In [29]:
cars1 = Series(cars_dict)

In [30]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [31]:
type(cars1)

pandas.core.series.Series

In [32]:
cars1 = Series({'Malibu': 40000, 'Lacetti': 20000, 'Toyota': 45000, 'Mazda':52000, 'Honda': 38000})

In [33]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [34]:
'Malibu' in cars1

True

In [35]:
'BMW' in cars1

False

In [36]:
cars1['Toyota']

np.int64(45000)

In [39]:
models = ['Honda', 'Mazda', 'Lacetti', 'Jagua', 'Malibu', 'Toyota', 'Hongi']

In [40]:
cars2 = Series(cars_dict, index=models)

In [41]:
cars_dict

{'Malibu': 40000,
 'Lacetti': 20000,
 'Toyota': 45000,
 'Mazda': 52000,
 'Honda': 38000}

In [42]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jagua          NaN
Malibu     40000.0
Toyota     45000.0
Hongi          NaN
dtype: float64

In [43]:
cars2.isnull() ## bu qiymat null (mavjud emasligini) tekshirish uchun

Honda      False
Mazda      False
Lacetti    False
Jagua       True
Malibu     False
Toyota     False
Hongi       True
dtype: bool

In [44]:
cars2.notnull() ## bu esa qiymat null emasligini (mavjudligini) tekshirish uchun ishlatiladi

Honda       True
Mazda       True
Lacetti     True
Jagua      False
Malibu      True
Toyota      True
Hongi      False
dtype: bool

In [45]:
cars2

Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jagua          NaN
Malibu     40000.0
Toyota     45000.0
Hongi          NaN
dtype: float64

In [46]:
cars1

Malibu     40000
Lacetti    20000
Toyota     45000
Mazda      52000
Honda      38000
dtype: int64

In [47]:
cars2 + cars1

Honda       76000.0
Hongi           NaN
Jagua           NaN
Lacetti     40000.0
Malibu      80000.0
Mazda      104000.0
Toyota      90000.0
dtype: float64

In [48]:
cars2.name = 'Avtosalon'

In [49]:
cars2.index.name = 'Modellar'

In [50]:
cars2

Modellar
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jagua          NaN
Malibu     40000.0
Toyota     45000.0
Hongi          NaN
Name: Avtosalon, dtype: float64

## `Series` obyektiga oid ba'zi parametrlar va metodlar

In [54]:
cars2

Modellar
Honda      38000.0
Mazda      52000.0
Lacetti    20000.0
Jagua          NaN
Malibu     40000.0
Toyota     45000.0
Hongi          NaN
Name: Avtosalon, dtype: float64

In [52]:
cars2.index # indexlar

Index(['Honda', 'Mazda', 'Lacetti', 'Jagua', 'Malibu', 'Toyota', 'Hongi'], dtype='object', name='Modellar')

In [55]:
cars2.values # qiymatlar

array([38000., 52000., 20000.,    nan, 40000., 45000.,    nan])

In [57]:
cars2.hasnans # nan qiymatlar borligini tekshiradi b/sa (True), aks holda (False)

True

In [59]:
cars2.dtype # qiymat ma'lumot turini bilish uchun

dtype('float64')

In [61]:
cars2.is_unique # bu qiymatlarni takrorlanmas ekanligini tekshiradi

False

In [63]:
cars2.shape #series hajmi

(7,)

In [65]:
cars2.size #series hajmi

7

In [66]:
cars2.iloc[2] #malumotni indeks raqami bo'yicha murojat qilish

np.float64(20000.0)

In [67]:
cars2[-2]

/tmp/ipykernel_185/3051620245.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cars2[-2]

np.float64(45000.0)

In [69]:
cars2['Lacetti'] # ma'lumotlarga indeks bo'yicha murojaat qilish

np.float64(20000.0)

In [73]:
cars2.loc['Mazda'] # ma'lumotlarga indeks bo'yicha murojaat qilish

np.float64(52000.0)

In [75]:
cars2.max() # max qiymat

52000.0

In [76]:
cars2.min() # min qiymat

20000.0

In [77]:
cars2.mean() # mean (o'rta) qiymatini topish

np.float64(39000.0)

In [79]:
cars1_dict = {'Malibu':'Gm moshinasi juda qulay', 'Lacetti':'Oldin chiqgan gm moshinasi', 'Toyota':'Yaponiyani mashhur mashinalaridan biri', 'Mazda':'Yangi moshina'} # bu lug'at

In [80]:
yangi = Series(cars1_dict)

In [81]:
yangi

Malibu                    Gm moshinasi juda qulay
Lacetti                Oldin chiqgan gm moshinasi
Toyota     Yaponiyani mashhur mashinalaridan biri
Mazda                               Yangi moshina
dtype: object

In [82]:
yangi.index

Index(['Malibu', 'Lacetti', 'Toyota', 'Mazda'], dtype='object')

In [83]:
yangi.values

array(['Gm moshinasi juda qulay', 'Oldin chiqgan gm moshinasi',
       'Yaponiyani mashhur mashinalaridan biri', 'Yangi moshina'],
      dtype=object)

In [84]:
yangi[2]

/tmp/ipykernel_185/2833842863.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  yangi[2]

'Yaponiyani mashhur mashinalaridan biri'

In [85]:
yangi['Mazda']

'Yangi moshina'