#Pandas kutubxonasidagi Data Frame ma'lumotlar tuzilmasi

In [1]:
import pandas as pd

In [4]:
data = {'Yili': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
        'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
        "Temp": [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]}

df = pd.DataFrame(data)

In [5]:
df

   Yili  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65
5  2016        31.4  1.66
6  2015        30.9  1.64
7  2010        28.5  1.53

In [6]:
df.head()

   Yili  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48
2  2019        32.9  1.56
3  2018        32.5  1.62
4  2017        31.9  1.65

In [7]:
df.head(2)

   Yili  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.48

In [8]:
df.shape

(8, 3)

In [9]:
df = pd.DataFrame(data, columns=['Yil', 'Temp', "Aholi soni"])

In [10]:
df.head()

   Yil  Temp  Aholi soni
0  NaN  1.54        33.9
1  NaN  1.48        33.5
2  NaN  1.56        32.9
3  NaN  1.62        32.5
4  NaN  1.65        31.9

In [11]:
df = pd.DataFrame(data, columns=['Yil', 'Temp', "Aholi soni", 'YAIM'], index=[20, 12, 25, 45, 65, 85, 99, 77])

In [12]:
df

    Yil  Temp  Aholi soni YAIM
20  NaN  1.54        33.9  NaN
12  NaN  1.48        33.5  NaN
25  NaN  1.56        32.9  NaN
45  NaN  1.62        32.5  NaN
65  NaN  1.65        31.9  NaN
85  NaN  1.66        31.4  NaN
99  NaN  1.64        30.9  NaN
77  NaN  1.53        28.5  NaN

In [13]:
aholi = df["Aholi soni"]

In [14]:
aholi

20    33.9
12    33.5
25    32.9
45    32.5
65    31.9
85    31.4
99    30.9
77    28.5
Name: Aholi soni, dtype: float64

In [15]:
type(aholi)

pandas.core.series.Series

In [16]:
df.Temp

20    1.54
12    1.48
25    1.56
45    1.62
65    1.65
85    1.66
99    1.64
77    1.53
Name: Temp, dtype: float64

In [17]:
df.YAIM = 0

In [18]:
df

    Yil  Temp  Aholi soni  YAIM
20  NaN  1.54        33.9     0
12  NaN  1.48        33.5     0
25  NaN  1.56        32.9     0
45  NaN  1.62        32.5     0
65  NaN  1.65        31.9     0
85  NaN  1.66        31.4     0
99  NaN  1.64        30.9     0
77  NaN  1.53        28.5     0

In [19]:
val = pd.Series([1800, 2500, 4500, 7898], index=[20, 12, 65, 77])
df.YAIM = val

In [20]:
df

    Yil  Temp  Aholi soni    YAIM
20  NaN  1.54        33.9  1800.0
12  NaN  1.48        33.5  2500.0
25  NaN  1.56        32.9     NaN
45  NaN  1.62        32.5     NaN
65  NaN  1.65        31.9  4500.0
85  NaN  1.66        31.4     NaN
99  NaN  1.64        30.9     NaN
77  NaN  1.53        28.5  7898.0

In [21]:
val2 = [1800, 2500, 1450, 5445, 4500, 8888, 7777, 7889]
df.YAIM = val2

In [22]:
df

    Yil  Temp  Aholi soni  YAIM
20  NaN  1.54        33.9  1800
12  NaN  1.48        33.5  2500
25  NaN  1.56        32.9  1450
45  NaN  1.62        32.5  5445
65  NaN  1.65        31.9  4500
85  NaN  1.66        31.4  8888
99  NaN  1.64        30.9  7777
77  NaN  1.53        28.5  7889

In [23]:
df['4000+'] = df.YAIM > 4000

In [24]:
df

    Yil  Temp  Aholi soni  YAIM  4000+
20  NaN  1.54        33.9  1800  False
12  NaN  1.48        33.5  2500  False
25  NaN  1.56        32.9  1450  False
45  NaN  1.62        32.5  5445   True
65  NaN  1.65        31.9  4500   True
85  NaN  1.66        31.4  8888   True
99  NaN  1.64        30.9  7777   True
77  NaN  1.53        28.5  7889   True

In [25]:
del df['4000+']

In [26]:
df

    Yil  Temp  Aholi soni  YAIM
20  NaN  1.54        33.9  1800
12  NaN  1.48        33.5  2500
25  NaN  1.56        32.9  1450
45  NaN  1.62        32.5  5445
65  NaN  1.65        31.9  4500
85  NaN  1.66        31.4  8888
99  NaN  1.64        30.9  7777
77  NaN  1.53        28.5  7889

In [27]:
data = {'Uzbekistan': {2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
        'Kazakhstan': {2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}}
df2 = pd.DataFrame(data)

In [28]:
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [29]:
df2.index.name = 'Yil'

In [30]:
df2

      Uzbekistan  Kazakhstan
Yil
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [31]:
df2 = pd.DataFrame(data, index=[2021, 2019, 2017])

In [32]:
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [33]:
df2.T

            2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1

In [34]:
array = df2.values

In [35]:
array

array([[33.9, 18.9],
       [32.9, 18.5],
       [31.9, 18.1]])

In [36]:
type(array)

numpy.ndarray

In [37]:
df2.index

Index([2021, 2019, 2017], dtype='int64')

In [38]:
df

    Yil  Temp  Aholi soni  YAIM
20  NaN  1.54        33.9  1800
12  NaN  1.48        33.5  2500
25  NaN  1.56        32.9  1450
45  NaN  1.62        32.5  5445
65  NaN  1.65        31.9  4500
85  NaN  1.66        31.4  8888
99  NaN  1.64        30.9  7777
77  NaN  1.53        28.5  7889

In [39]:
df.index

Index([20, 12, 25, 45, 65, 85, 99, 77], dtype='int64')

In [40]:
df.columns

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='object')

In [41]:
indeks = df.columns

In [42]:
indeks

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='object')

In [43]:
'Yil' in indeks

True

In [44]:
df2

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2019        32.9        18.5
2017        31.9        18.1

In [45]:
'Tajikistan' in df2.columns

False

In [46]:
2021 in df2.index

True

In [47]:
indeks

Index(['Yil', 'Temp', 'Aholi soni', 'YAIM'], dtype='object')

In [48]:
indeks[0]

'Yil'

In [49]:
indeks[2:4]

Index(['Aholi soni', 'YAIM'], dtype='object')

In [50]:
data1 = {'Uzbekistan': {2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
        'Kazakhstan': {2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}}
df = pd.DataFrame(data)

In [51]:
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [52]:
usernames = {"bahodir":"bshodir1234", "olim":"olimtoy", "maryam":"5444", "nodira":"4466"}
emails = {"bahodir":"bahodir@2001", "olim":"olim@mail.ru", "maryam":"maryam1234", "nodira":"nodira@666gmail.com"}

In [53]:
data = {'usernames': usernames, 'emails':emails}
df = pd.DataFrame(data)

In [54]:
df

           usernames               emails
bahodir  bshodir1234         bahodir@2001
olim         olimtoy         olim@mail.ru
maryam          5444           maryam1234
nodira          4466  nodira@666gmail.com

In [55]:
df.index

Index(['bahodir', 'olim', 'maryam', 'nodira'], dtype='object')

In [56]:
arr = ['bahodir', 'olim', 'maryam', 'nodira']

In [57]:
arr[1]

'olim'

In [58]:
data2 = {'usernames': {'olim':'olimjonov21', "maryam":'maryam2020'},
         'emails':{'olim':'olimjonov21@gmail.ru', "maryam":'maryam2020@gmail.com'}}

In [59]:
df2 = pd.concat([df, pd.DataFrame(data2)])
df2

           usernames                emails
bahodir  bshodir1234          bahodir@2001
olim         olimtoy          olim@mail.ru
maryam          5444            maryam1234
nodira          4466   nodira@666gmail.com
olim     olimjonov21  olimjonov21@gmail.ru
maryam    maryam2020  maryam2020@gmail.com

In [60]:
newmind = pd.Index(['olim', 'soliha', 'jasmina', 'Muxsina'])
newmind.isin(df2.index)

array([ True, False, False, False])

In [61]:
df2.index.difference(newmind)

Index(['bahodir', 'maryam', 'nodira'], dtype='object')

In [62]:
newmind.difference(df2.index)

Index(['Muxsina', 'jasmina', 'soliha'], dtype='object')

#union()

In [63]:
df2.index.union(newmind)

Index(['Muxsina', 'bahodir', 'jasmina', 'maryam', 'maryam', 'nodira', 'olim',
       'olim', 'soliha'],
      dtype='object')

#delete()

In [64]:
df2.index.delete(0)

Index(['olim', 'maryam', 'nodira', 'olim', 'maryam'], dtype='object')

#drop()

In [65]:
newmind.drop('soliha')

Index(['olim', 'jasmina', 'Muxsina'], dtype='object')

In [66]:
newmind

Index(['olim', 'soliha', 'jasmina', 'Muxsina'], dtype='object')

In [67]:
df2.index

Index(['bahodir', 'olim', 'maryam', 'nodira', 'olim', 'maryam'], dtype='object')

.insert()

In [68]:
df2.index.insert(4, 'Suraya')

Index(['bahodir', 'olim', 'maryam', 'nodira', 'Suraya', 'olim', 'maryam'], dtype='object')

#.is_monotonic() va .is_unique()

In [69]:
df2.index.is_monotonic_decreasing

False

In [70]:
df2.index.is_unique

False

In [71]:
newmind

Index(['olim', 'soliha', 'jasmina', 'Muxsina'], dtype='object')

In [72]:
newmind.is_unique

True

#uniqu()

In [73]:
df2.index.unique() ## takrorlanmas elementlar

Index(['bahodir', 'olim', 'maryam', 'nodira'], dtype='object')