###Indekslash, qator (ustun) tanlash, filtirlash

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
data = {'Yili': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
        'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
        "Temp": [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
        'Zichlik': [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}
df = pd.DataFrame(data)
df

   Yili  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [6]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]

In [7]:
data = df['Aholi soni']

In [8]:
data

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [9]:
type(data)

pandas.core.series.Series

In [10]:
data1 = df[['Aholi soni']]

In [11]:
data1

    Aholi soni
21        33.9
20        33.5
19        32.9
18        32.5
17        31.9
16        31.4
15        30.9
10        28.5

In [12]:
type(data1)

pandas.core.frame.DataFrame

In [13]:
data

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [14]:
data[16]

np.float64(31.4)

In [15]:
type(data[16])

numpy.float64

In [16]:
data[[16]]

16    31.4
Name: Aholi soni, dtype: float64

In [17]:
type(data[[16]])

pandas.core.series.Series

In [18]:
x = data[21]
x

np.float64(33.9)

In [19]:
x + 20

np.float64(53.9)

In [20]:
data

21    33.9
20    33.5
19    32.9
18    32.5
17    31.9
16    31.4
15    30.9
10    28.5
Name: Aholi soni, dtype: float64

In [21]:
data[0:4]

21    33.9
20    33.5
19    32.9
18    32.5
Name: Aholi soni, dtype: float64

In [22]:
data[[21, 20, 19, 18]]

21    33.9
20    33.5
19    32.9
18    32.5
Name: Aholi soni, dtype: float64

In [23]:
obj = pd.Series(np.arange(8.), index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [24]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [25]:
obj['a']

np.float64(0.0)

In [26]:
obj[['a']]

a    0.0
dtype: float64

In [27]:
obj[0:4]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [28]:
obj['a':'f']

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [29]:
obj[[1, 4]]

/tmp/ipykernel_233/1388052521.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 4]]

b    1.0
e    4.0
dtype: float64

In [30]:
obj['a':'c']=6

In [31]:
obj

a    6.0
b    6.0
c    6.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [32]:
obj[obj<6]

d    3.0
e    4.0
f    5.0
dtype: float64

In [33]:
uz = {2020:33.5, 2019:33.2, 2018:32.5, 2017:31.9, 2016:31.4, 2015:30.9}
kz = {2020:18.8, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8, 2015:17.6}
tj = {2020:9.5, 2019:9.3, 2018:9.1, 2017:8.9, 2016:8.7, 2015:8.5}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.2, 2016:6.1, 2015:6.0}
tr = {2020:6.0, 2019:5.9, 2018:5.9, 2017:5.8, 2016:5.6, 2015:5.6}

df = pd.DataFrame(
    {
        'Uzbekistan':uz,
        'Kazakhstan':kz,
        'Tajikiston':tj,
        'Kyrgizstan':kg,
        'Turkmenistan':tr

    }
)

In [34]:
df

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        33.2        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [35]:
df['Uzbekistan']

2020    33.5
2019    33.2
2018    32.5
2017    31.9
2016    31.4
2015    30.9
Name: Uzbekistan, dtype: float64

In [36]:
df[['Uzbekistan']]

      Uzbekistan
2020        33.5
2019        33.2
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [37]:
df['Uzbekistan'].to_numpy()

array([33.5, 33.2, 32.5, 31.9, 31.4, 30.9])

In [38]:
df[['Uzbekistan']].to_numpy()

array([[33.5],
       [33.2],
       [32.5],
       [31.9],
       [31.4],
       [30.9]])

In [39]:
df[['Uzbekistan', 'Turkmenistan']]

      Uzbekistan  Turkmenistan
2020        33.5           6.0
2019        33.2           5.9
2018        32.5           5.9
2017        31.9           5.8
2016        31.4           5.6
2015        30.9           5.6

In [40]:
df[3:]

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [41]:
df

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        33.2        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [42]:
df>10

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        True        True       False       False         False
2019        True        True       False       False         False
2018        True        True       False       False         False
2017        True        True       False       False         False
2016        True        True       False       False         False
2015        True        True       False       False         False

In [43]:
df>5

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        True        True        True        True          True
2019        True        True        True        True          True
2018        True        True        True        True          True
2017        True        True        True        True          True
2016        True        True        True        True          True
2015        True        True        True        True          True

In [44]:
df>7

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        True        True        True       False         False
2019        True        True        True       False         False
2018        True        True        True       False         False
2017        True        True        True       False         False
2016        True        True        True       False         False
2015        True        True        True       False         False

In [45]:
df

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        33.2        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [46]:
df>6.3

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        True        True        True        True         False
2019        True        True        True        True         False
2018        True        True        True       False         False
2017        True        True        True       False         False
2016        True        True        True       False         False
2015        True        True        True       False         False

In [47]:
df[['Uzbekistan']][df['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        33.2
2018        32.5

In [48]:
dfuz = df[['Uzbekistan']]

In [49]:
dfuz

      Uzbekistan
2020        33.5
2019        33.2
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [50]:
dfuz[dfuz['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        33.2
2018        32.5

In [51]:
dfuz['Uzbekistan']>32

2020     True
2019     True
2018     True
2017    False
2016    False
2015    False
Name: Uzbekistan, dtype: bool

In [52]:
df2 = df.transpose(copy=True)

In [53]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  33.2  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikiston     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgizstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [54]:
df2[df2[2015]>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  33.2  32.5  31.9  31.4  30.9
Kazakhstan  18.8  18.5  18.3  18.1  17.8  17.6
Tajikiston   9.5   9.3   9.1   8.9   8.7   8.5

In [55]:
df2[df2[2015]<8]

              2020  2019  2018  2017  2016  2015
Kyrgizstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [56]:
pd = pd.Series([2, 8, 6, 9, 77, 558])
pd

0      2
1      8
2      6
3      9
4     77
5    558
dtype: int64

In [57]:
type(pd.to_numpy())

numpy.ndarray

In [58]:
type(pd.tolist())

list

In [59]:
import pandas as pd
a = pd.Series([2, 4, 6, 8, 10])

In [60]:
a

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [61]:
b = pd.Series([1, 3, 5, 7, 9])

In [62]:
b

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [63]:
c = a + b

In [64]:
c

0     3
1     7
2    11
3    15
4    19
dtype: int64

##.loc va .iloc

In [66]:
df

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        33.2        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [67]:
df['Kazakhstan']

2020    18.8
2019    18.5
2018    18.3
2017    18.1
2016    17.8
2015    17.6
Name: Kazakhstan, dtype: float64

In [69]:
df.loc[[2016]]

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2016        31.4        17.8         8.7         6.1           5.6

In [70]:
df.loc[[2020, 2018]]

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2018        32.5        18.3         9.1         6.3           5.9

In [72]:
df.loc[[2015,2020], ['Uzbekistan', 'Tajikiston']]

      Uzbekistan  Tajikiston
2015        30.9         8.5
2020        33.5         9.5

In [74]:
df.iloc[[0, 4],[0, 3]]

      Uzbekistan  Kyrgizstan
2020        33.5         6.5
2016        31.4         6.1

In [75]:
df

      Uzbekistan  Kazakhstan  Tajikiston  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        33.2        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [76]:
df.at[2016, 'Uzbekistan']

np.float64(31.4)

In [77]:
df.at[2020, 'Uzbekistan']

np.float64(33.5)

In [78]:
df.at[2020, 'Uzbekistan'] - df.at[2016, 'Uzbekistan']

np.float64(2.1000000000000014)

In [79]:
df.iat[2, 1]

np.float64(18.3)

In [84]:
nums = list(range(10, 30))

In [85]:
nums

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [86]:
nums[0]

10

In [87]:
nums[-1]

29

In [90]:
obj = pd.Series(np.arange(10.))

In [91]:
obj

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [92]:
obj[0]

np.float64(0.0)

In [98]:
ser = pd.Series(np.arange(6.), index=['a', 'b', 'c', 'd', 'e', 'f'])

In [99]:
ser

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [100]:
ser[0]

/tmp/ipykernel_233/2519058933.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[0]

np.float64(0.0)

In [101]:
ser[-1]

/tmp/ipykernel_233/3387420178.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[-1]

np.float64(5.0)

In [103]:
ser.iloc[-1]

np.float64(5.0)

In [104]:
obj

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [106]:
obj.iloc[-1]

np.float64(9.0)